fixing workflow file

diff --git a/.github/workflows/chalk-and-push.yml b/.github/workflows/chalk-and-push.yml
--- a/.github/workflows/chalk-and-push.yml
+++ b/.github/workflows/chalk-and-push.yml
@@ -136,18 +136,24 @@ jobs:
           fetch-depth: 0
           ref: ${{ inputs.commit || inputs.branch || github.ref }}
 
-      #      - name: Enable debug
-      #        if: always()
-      #        shell: bash
-      #        run: |
-      #          echo "CURIOSITY_STRACE=/mnt/curiosity/co-strace" >> $GITHUB_ENV
-
       - name: Setup Chalk
         uses: crashappsec/setup-chalk-action@main
         with:
           connect: true
           version: latest
           latest_version_url: https://dl.crashoverride.run/crashoverride/chalk/current-version.txt
+
+      - name: Load environment variables from .env file
+        run: |
+          if [ -f .env ]; then
+            # Filter out comments and empty lines, then add each variable to $GITHUB_ENV
+            grep -vE '^\s*#|^\s*$' .env | while read -r line; do
+              echo "$line" >> $GITHUB_ENV
+            done
+          else
+            echo ".env file not found!"
+            exit 1
+          fi
 
       - name: Assume AWS Role
         id: role
